# Generated by Django 5.0.2 on 2024-02-27 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("totalCharge", models.IntegerField(default=0)),
                ("totalMembers", models.IntegerField(default=0)),
                ("link", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("display_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("totalOwed", models.IntegerField()),
                ("paid", models.BooleanField(default=False)),
                ("cardNumber", models.IntegerField()),
                ("cardSecurity", models.IntegerField()),
                ("cardExpiration", models.DateField()),
                ("streetAddress", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=2)),
                ("zipCode", models.IntegerField()),
                ("country", models.CharField(max_length=100)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="splitly_api.group",
                    ),
                ),
                (
                    "payer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="splitly_api.user",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="group",
            name="leader",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leader",
                to="splitly_api.user",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="userList",
            field=models.ManyToManyField(
                through="splitly_api.Transaction", to="splitly_api.user"
            ),
        ),
    ]
