# Generated by Django 5.0.2 on 2024-02-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("splitly_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="cardExpiration",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="cardNumber",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="cardSecurity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="state",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="streetAddress",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="zipCode",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
